version: "3.38.0"

tasks:
  serve:
    desc: "Serves the Angular app locally for development."
    cmds:
      - "pnpm ng serve"

  build:
    desc: "Builds the Angular app."
    requires:
      vars: [ENV]
    cmds:
      - "pnpm ng build --configuration {{.ENV}}"
