version: "3.38.0"

tasks:
  serve:
    desc: "Serves the Angular app locally for development."
    cmds:
      - "pnpm ng serve"

  serve:ssr:
    desc: "Serves the Angular app locally using Server Side Rendering."
    cmds:
      - "node dist/portfolio/server/server.mjs"

  build:
    desc: "Builds the Angular app."
    requires:
      vars: [ENV]
    cmds:
      - "pnpm ng build --configuration {{.ENV}}"

  deploy:
    desc: "Deploy the Angular app."
    requires:
      vars: [ENV, AWS_PROFILE, INFRASTRUCTURE_PREFIX, DISTRIBUTION_ID]
    cmds:
      - aws s3 sync ./dist/portfolio/browser s3://$INFRASTRUCTURE_PREFIX-bucket-frontend-static-files --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" > /dev/null
