version: "3.38.0"

dotenv: [".env.{{.DOTENV}}"]

includes:
  iac:
    dir: ./iac
    taskfile: ./iac
  api:
    dir: ./docs/api
    taskfile: ./docs/api
  lambda:
    dir: ./backend
    taskfile: ./backend
  front:
    dir: ./frontend
    taskfile: ./frontend

tasks:
  install-node-dependencies:
    desc: "Install node dependencies."
    internal: true
    cmds:
      - pnpm install

  install-python-dependencies:
    desc: "Install python dependencies."
    internal: true
    cmds:
      - poetry install

  install:
    desc: "Install all dependencies."
    deps: [install-python-dependencies, install-node-dependencies]
