version: "3.38.0"

dotenv: [".env.{{.DOTENV}}"]

includes:
  iac:
    dir: ./iac
    taskfile: ./iac
  api:
    dir: ./docs/api
    taskfile: ./docs/api
  lambda:
    dir: ./backend
    taskfile: ./backend
  front:
    dir: ./frontend
    taskfile: ./frontend
