version: "3.38.0"

tasks:
  build:
    desc: "Bundle the lambda function for deployment."
    cmds:
      - rm -rf ./build
      - pnpm tsc -p ./tsconfig.app.json
      - pnpm tsc-alias -p tsconfig.app.json
