version: "3.38.0"

tasks:
  lint:
    desc: "Lint the API specification against best practices."
    cmds:
      - pnpm redocly lint ./api.yaml --config redocly.yaml

  build:
    desc: "Bundle the API specification into a single file for deployment."
    cmds:
      - pnpm redocly bundle ./api.yaml -o ./build/api.yaml --config redocly.yaml

  serve:
    desc: "Preview the API documentation in a local environment."
    cmds:
      - pnpm redocly preview-docs ./api.yaml --config redocly.yaml --skip-decorator=aws-api-gateway-postprocess/remove-dots

  deploy:
    desc: "Deploy the REST API."
    requires:
      vars: [ENV, AWS_REGION, REST_API_ID]
    cmds:
      - aws apigateway create-deployment --rest-api-id "$REST_API_ID" --stage-name "$ENV" --region "$AWS_REGION"
